### ISSUE TITLE
Project setup or garden

### ISSUE THREAD

**Issue by AndreMiras** [Enteleform/-Kivy-MarginLayout-Demo#1]
Interesting demo thank you.
Why not pushing it further and either making or setup or a garden?

**Comment by Enteleform** [comment]
Haven't been doing much Kivy-ing / Python-ing these days due to brittle deployment / build systems (*compared to AndroidStudio, Xamarin, Node, etc.*). Feel free to modify this & throw it in Kivy Garden if you want.

I had actually mentioned it in the dev forum and one of the devs seemed receptive to baking this functionality into core, pending some testing @ the Kivy Garden level. See: https://groups.google.com/forum/#!searchin/kivy-dev/margin%7Csort:date/kivy-dev/fsR1m3_rVj8/F2OGSHjfAQAJ

**Comment by AndreMiras** [comment]
Thank you for such a quick feedback. Yes I cannot agree more regarding the "brittleness", but this is also what attracts me, it gives a lot of room to contributions :)

> Feel free to modify this & throw it in Kivy Garden if you want.
OK, I'll work on that now and of course give you the credits!
